---
version: "3.9"

networks:
  finnet:
    name: finnet
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          ip_range: 172.25.5.0/24
          gateway: 172.25.0.1

services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    environment:
     - TERM=linux
     - GF_INSTALL_PLUGINS=grafana-clock-panel
    user: '1000'
    ports:
     - '3000:3000'
    volumes:
     - '$PWD/dist/grafana:/var/lib/grafana'
    networks:
      - finnet
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finances
    volumes:
      - ./dist/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: no
    ports:
      - "5432:5432"
    # Allow localhost connections
    networks:
      - finnet
    extra_hosts:
      - "host.docker.internal:host-gateway"
