interpreter = ["sh", "-euo", "pipefail", "-c"]

[[task]]
name = "engage"
group = "versions"
script = "engage --version"

[[task]]
name = "nix"
group = "versions"
script = "nix --version"

[[task]]
name = "direnv"
group = "versions"
script = "direnv --version"

[[task]]
name = "python"
group = "versions"
script = "python --version"

[[task]]
name = "poetry"
group = "versions"
script = "poetry --version"

[[task]]
name = "black"
group = "versions"
script = "black --version"

[[task]]
name = "ruff"
group = "versions"
script = "ruff --version"

[[task]]
name = "nixpkgs-fmt"
group = "versions"
script = "nixpkgs-fmt --version 2> /dev/null"
# This always exits 1 for some reason
ignore = [ 1 ]

[[task]]
name = "markdownlint"
group = "versions"
script = "markdownlint --version"

[[task]]
name = "markdownlint"
group = "lints"
script = "markdownlint -i .venv ."

[[task]]
name = "nixpkgs-fmt"
group = "lints"
script = "nixpkgs-fmt --check ."

[[task]]
name = "black"
group = "lints"
script = "black --check --diff --color ."

[[task]]
name = "ruff"
group = "lints"
script = "ruff check ."

[[task]]
name = "pyright"
group = "lints"
script = "pyright"

[[task]]
name = "pytest"
group = "tests"
script = """
pytest \
    --color yes \
    --cov finlit \
    --cov-report term
"""
# Exit code 5 means no tests were collected, which shouldn't really fail CI
ignore = [ 5 ]
